### PR TITLE
Project/Environments Routing Fixes

### LINKED ISSUE #249: User can navigate to project pages before selecting environment
**Describe the bug**
Once a user lands on {project}/environment they can click on the project links in the left nav.
If they do this before they've selected an environment, then the environment is never reflected in the url. Its ambiguous which environment is selected based on the uri and hard to tell which is inaccurate.

### LINKED ISSUE #250: Hide Project Menu when Not Viewing Project
**Describe the bug**
If you visit a project, the project options appear in the left nav. If you go back to the dashboard or admin pages, the project menu options are still open. These options should disappear when the user navigates away from it.

### PR DESCRIPTION
**Pull request by aballman**
* Simplified routing rules or Project vs ProjectEnvironment
* Fixed projects menu appearing inappropriately (Fixes #250) 
* Updated Admin dropdown menu to be more visually indicative
* Fixed typography errors attempting to use 'headline' component instead of variant

Fixes #249 (User can navigate to project before selecting environment)

project-routing-fixes

### CODE REVIEW

File: src/components/Project/Environment/index.js [hunk 1]
```diff
@@ -82,38 +82,46 @@ export default class Environment extends React.Component {
...
-    environments.map((env) => {
-      if(env.key === currentEnv.key || env.key === this.props.match.params.environment){
-        matched = true
-        
-        if(!currentEnv.key) {
+    let environmentName = null
+
+    environments.forEach((env) => {
+      if(env.key === this.props.match.params.environment || (!!currentEnv && currentEnv.key === env.key)){
+        if(!currentEnv.key || currentEnv.key !== env.key) {
```
Comment (drshrey) [inline src/components/Project/Environment/index.js]: could we add a comment here to clarify what's going on here?

File: src/components/Project/index.js [hunk 2]
```diff
@@ -154,51 +154,59 @@ class Project extends React.Component {
...
-          slug: this.props.match.url + "/settings",
+          slug: `${props.match.url}/${currentEnv}/settings`,
         },
     ];
   }
 
   componentWillReceiveProps(nextProps) {
-    this.setLeftNavProjectItems(nextProps)
+    let currentEnv = this.props.store.app.currentEnvironment
+    if (!!currentEnv && !!currentEnv.key) {
```
Comment (drshrey) [inline src/components/Project/index.js]: I will make an issue to change all other truthiness checks in this code to this format
