### PR TITLE
Fixes Two Panel Bugs Concerning Create Projects

### LINKED ISSUE #271: Github SSH Key Link Broken
**Describe the bug**
A new project without any releases displays a link to add the SSH key to GIthub. Utilizing this link results in nothing happening.

**To Reproduce**
1. Create a private project
2. Observe the link on the empty 'releases' page 
3. Utilize the link, observe it is non functional

### PR DESCRIPTION
**Pull request by amoskyler**
fixes #271 & #283

### CODE REVIEW

File: src/components/Project/Features/index.js [hunk 1]
```diff
@@ -160,7 +160,7 @@ export default class Features extends React.Component {
                 Make sure all relevant features are pushed into {project.gitBranch}. 
                 {project.gitProtocol === "SSH" &&
                   <div>
-                  If you haven't done so already, <NavLink to={"/projects/" + project.slug + "/settings"}><strong> make sure your deploy key is added in your git settings.</strong></NavLink>
+                  If you haven't done so already, <NavLink to={"/projects/" + project.slug + "/" + this.props.store.app.currentEnvironment.name + "/settings"}><strong> make sure your deploy key is added in your git settings.</strong></NavLink>
```
Comment (aballman) [inline src/components/Project/Features/index.js]: This would be cool ````/projects/${project.slug}/${this.props.store.app.currentEnvironment.name}/settings````
but I'm not block you over it.

Comment (aballman) [reply src/components/Project/Features/index.js]: You have to use backticks though instead of double-quotes.

Comment (amoskyler) [reply src/components/Project/Features/index.js]: Indeed, I have switched it to using string interpolation.
