### PR TITLE
Fix issue when visiting a project page with a direct link 

### LINKED ISSUE #303: Going on project services link directly loads no services
some useful info: EnvironmentID parameter is null when I inspect request payload

### PR DESCRIPTION
**Pull request by aballman**
* Fixes #303
* The issue occurs because the elements reference the app store which is not configured correctly with a direct link.
* Fixes issue with React when timer tries to set state after component has been unmounted for Project/Releases

Solution: Have the components use the `environment` prop that is handed down from the environment selector. If the app store is set, then use that. If not, then try to parse the url slug to get the current environment. If that doesn't parse or it's not an environment the project supports, then present user with the environment selection screen.

### CODE REVIEW

File: src/components/Project/index.js [hunk 1]
```diff
@@ -300,22 +300,22 @@ class Project extends React.Component {
         </Grid>
         <Switch>
           <Route exact path='/projects/:slug/:environment/features' render={(props) => (
-            <ProjectFeatures history={history} socket={socket} {...props} />
+            <ProjectFeatures history={history} socket={socket} {...props} environment={this.props.environment}/>
```
Comment (drshrey) [inline src/components/Project/index.js]: since we're passing in `...props`, is there anyway environment can be extracted from within there?
