### PR TITLE
Route53 Labels

### LINKED ISSUE #189: Route 53 Plugin Load Balancer List List is Generic
**Describe the bug**
Users cannot tell which load balancer their Route 53 plugin is referencing.

**Expected behavior**
I would like to see which services/LB addresses are being referenced when clicking on the load balancer drop down menu

**Screenshots**
image

### PR DESCRIPTION
**Pull request by aballman**
* Adds labels to Route53 Load Balancer Selection
** You can now see what the FQDN/DNS name of the load balancer is before selecting.

Fixes #189

### CODE REVIEW

**Comment by aballman** [comment]
Also Fixes #173

File: src/components/Project/Extensions/Route53/index.js [hunk 1]
```diff
@@ -196,14 +196,18 @@ export default class LoadBalancer extends React.Component {
...
+      let artifact = _.find(extension.artifacts, function(a) { return a.key === "dns" });
+      if (!artifact) {
+        return
+      }
+      let dns = artifact.value
       if(extension.extension.key.includes("loadbalancer") && extension.customConfig.type !== "internal") {
         extraOptions.push({
           key: extension.id,
-          value: extension.extension.name,
+          value: extension.extension.name + " (" + dns + ")",
```
Comment (seanmccann) [inline src/components/Project/Extensions/Route53/index.js]: @aballman You can use string interpolation:
```
value: `${extension.extension.name} (${dns})`
```

File: src/components/Project/Extensions/Route53/index.js [hunk 2]
```diff
@@ -196,14 +196,18 @@ export default class LoadBalancer extends React.Component {
     }
     
     var extraOptions = []
-    project.extensions.map(function(extension){
+    project.extensions.forEach(function(extension){
+      let artifact = _.find(extension.artifacts, function(a) { return a.key === "dns" });
+      if (!artifact) {
+        return
+      }
+      let dns = artifact.value
```
Comment (seanmccann) [inline src/components/Project/Extensions/Route53/index.js]: use `const` not `let`

File: src/components/Project/Extensions/Route53/index.js [hunk 3]
```diff
@@ -196,14 +196,18 @@ export default class LoadBalancer extends React.Component {
     }
     
     var extraOptions = []
-    project.extensions.map(function(extension){
+    project.extensions.forEach(function(extension){
```
Comment (seanmccann) [inline src/components/Project/Extensions/Route53/index.js]: Something like this uses the new ES6 styntax and may be a bit easier to maintain:

```
const { extensions } = project
const dns = extensions.find(ext => ext.key === 'dns')
const internalLoadbalancers = extensions.filter(ext => {
  return extension.extension.key.includes("loadbalancer")
    && extension.customConfig.type !== "internal"
})
const extraOptions = internalLoadbalancers.map(ext =>
  {
    key: ext.id,
    value: `${ext.extension.name} (${dns})`
  }
)
```
