### PR TITLE
Fix 'project create' error report

### LINKED ISSUE #186: Create Project doesn't bubble up Error Messages
**Describe the bug**
If there's an error during project creation, there is no front-facing error message to let the user know why project creation wasn't successful.

**To Reproduce**
1. Go to `/create`
2. Enter a url of a project that already exists
3. Click on the *CREATE* button.

**Expected behavior**
When I click on *CREATE*, there should be an error message telling me the project has already been created.

**Desktop (please complete the following information):**
- Chrome browser

### PR DESCRIPTION
**Pull request by aballman**
* Disable Mutation Error Policy
* Added Snackbar notice in error handler for mutation
* Fixed Snackbar prop to include correct prop name `SnackBarContentProps` to `ContentProps`
* Updated Snackbar CSS since the contentprops wasn't being applied properly before. It looked odd.

Fixes #186

### CODE REVIEW

File: src/lib/apollo.js [hunk 1]
```diff
@@ -67,9 +67,10 @@ export default (GRAPHQL_URI = process.env.REACT_APP_CIRCUIT_URI + '/query') => {
       query: {
         errorPolicy: 'apollo-link',
       },
-      mutate: {
-        errorPolicy: 'all',  
-      },
+      // https://github.com/apollographql/apollo-client/issues/3336
+      // mutate: {
```
Comment (amoskyler) [inline src/lib/apollo.js]: if possible please explicitly set to default value, leaving the issue reference. Otherwise, this should be fine.
